services:
  grafana:
    image: grafana/grafana:latest
    container_name: monitoring-grafana
    env_file: ./master/grafana/.env
    ports:
      - "${FORWARD_GRAFANA_PORT}:3000"
    restart: unless-stopped
    volumes:
      - ./master/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./data/grafana-data:/var/lib/grafana
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - monitoring
      - global_backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  loki:
    image: grafana/loki:2.9.0
    container_name: monitoring-loki
    ports:
      - "${FORWARD_LOKI_PORT}:3100"
    restart: unless-stopped
    volumes:
      - ./data/loki-data:/loki
      - ./master/loki/loki-config.yaml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/loki-config.yaml -config.expand-env=true
    networks:
      - monitoring
  
  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring-prometheus
    restart: unless-stopped
    volumes:
      - ./master/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./data/prometheus-data:/prometheus
    ports:
      - "${FORWARD_PROMETHEUS_PORT}:9090"
    networks:
      - monitoring
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
    cpus: 0.2
    mem_limit: 512M

  n8n:
    image: n8nio/n8n:latest
    container_name: tools-n8n
    restart: unless-stopped
    ports:
      - "${FORWARD_N8N_PORT}:5678"
    environment:
      # Basic
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production

      # Auth
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123

      # Timezone
      - GENERIC_TIMEZONE=Asia/Jakarta
      - TZ=Asia/Jakarta

    volumes:
      - ./data/n8n-data:/home/node/.n8n
    networks:
      - global_backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    cpus: 0.2
    mem_limit: 512M

  whatsapp:
    image: aldinokemal2104/go-whatsapp-web-multidevice
    container_name: tools-whatsapp
    restart: unless-stopped
    ports:
      - "${FORWARD_WHATSAPP_PORT}:3000"
    volumes:
      - whatsapp:/app/storages
    command:
      - rest
      - --basic-auth=admin:admin
      - --port=3000
      - --debug=true
      - --os=Chrome
      - --account-validation=false
    networks:
      - global_backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    cpus: 0.2
    mem_limit: 512M

volumes:
  whatsapp:

networks:
  monitoring:
    name: monitoring
    external: true
  global_backend:
    name: global_backend
    external: true